stages:
  - build
  - test 

variables:
  DOCKER_REGISTRY: "registry.pwlab.dev"
  NEXUS_PASSWORD: "YOUR-PASSWORD" # I wouldn't do this to a company. But for my personal educational purpose, this is fine
  NEXUS_USERNAME: "YOUR-USERNAME"
  IMAGE_NAME: "command-line-toolbox"
  TAG: 0.1.0
  HELM_REPO: "oci://helm.pwlab.dev"
  HELM_LOGIN_URL: "https://helm.pwlab.dev"

.default-before-script: &default-before-script 
  - 'echo "Runner info: $CI_RUNNER_DESCRIPTION"'
  - cat /etc/os-release
  - env | sort

build-docker-image:
  stage: build
  image: registry.pwlab.dev/build-tools:0.1.0
  tags:
    - kubernetes
  before_script:
    - *default-before-script
  script:
    - $CI_PROJECT_DIR/run/build_and_push.sh

build-helm-chart:
  stage: build
  image: registry.pwlab.dev/build-tools:0.1.0
  tags:
    - kubernetes
  before_script:
    - *default-before-script
  script:
    - $CI_PROJECT_DIR/run/helm_package.sh
    - $CI_PROJECT_DIR/run/helm_publish.sh